language: go

sudo: required

env:
  - HOME=/home/travis

services:
  - docker

go:
  - "1.18.10"

go_import_path: github.com/project-codeflare/multi-cluster-app-dispatcher

install: []


before_script:
  - export TEST_LOG_LEVEL=2

script:
  - BLUE='\033[34m'
  # Skip CI check when running as a pull request
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
          echo "Pull request build detected. Skipping CI flow.";
          exit 0;
          fi'
  - make mcad-controller
  - make run-test
  # Process 'make images' when NOT a pull request
  - 'if [ "$TRAVIS_PULL_REQUEST"  = "false" ]; then make images; fi'
  # Process 'make push-images' when NOT a pull request
  - 'if [[ "$TRAVIS_PULL_REQUEST" == "false"  &&  ! "$TRAVIS_BRANCH" =~ "^v[0-9]\.[0-9]+\.[0-9]+" ]]; then make push-images; fi'
  # Run the e2e and handle Travis condition where Travis fails on no output for 10 minutes.   No output for 10 minutes
  # is fine for our test cases that waits for 10 minutes before requeuing a job.  The other workaround was to
  # use 'travis_wait n' which unfortunately does not stream output until the very end so monitoring the Travis log 
  # during runtime is not possible.
  - make run-e2e &
  - PID=$! && echo -e "${BLUE}make run e2e pid=${PID}"
  - while [ -e /proc/${PID} ]; do echo -n "."  && sleep 30; done
  - wait ${PID}
