# This workflow will Build image and push to mcad quay repository and create a GitHub release tag

name: mcad Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true
        default: 'v0.0.0-dev'
        type: string
      quay-organization:
        description: 'Quay organization used to push the built images to'
        required: true
        default: 'project-codeflare'
        type: string

jobs:
  MCAD-CI:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set latest tag and Branch name
        run: |
          BRANCH= mcadCI/issue531test
          GIT_BRANCH=$(echo "$BRANCH" | sed 's/[^A-Za-z0-9._-]/-/g')"
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
          echo "TAG=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV
        shell: bash

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.10

      - name: Build
        run:
          make mcad-controller

      - name: Run Unit tests
        run: make run-test

      - name: Build Image
        run: |
          make images -e GIT_BRANCH=${{ env.GIT_BRANCH }} TAG=${{ env.GIT_BRANCH }}-${{ env.TAG }}

      - name: Run E2E tests
        run: |
          make run-e2e -e GIT_BRANCH=${{ env.GIT_BRANCH }} TAG=${{ env.GIT_BRANCH }}-${{ env.TAG }}

