# This workflow will Build image and push to mcad quay repository and create a GitHub release tag

name: mcad Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true
        default: 'v0.0.0-dev'
        type: string
      quay-organization:
        description: 'Quay organization used to push the built images to'
        required: true
        default: 'project'
        type: string

jobs:
  MCAD-CI:
    runs-on : ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.10

      - name: Build
        run: make mcad-controller

      - name: Unit tests
        run: make run-test

      - name: Image Build
        run: |
          make images

      - name: E2E tests
        run:  |
          make run-e2e